name: Lint

on: [push, pull_request]
jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        tofu-versions: [1.9.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ matrix['tofu-versions'] }}

      - name: Tofu fmt
        id: fmt
        run: tofu fmt -check
